### ISSUE TITLE
dynamic input shapes

### ISSUE THREAD

**Issue by ycbilge** [y-1111-y/P2Pnet_onnx#1]
Thanks for the code. I could not run the code with dynamic input shapes of the dataset shangaiTech. How did you run the code with given changing width and height of an image?
Thank you

**Comment by y-1111-y** [comment]
Thanks for your comment. Have you assigned the parameter "img-size" when you ran the export.py? Can you show me your error message?

**Comment by ycbilge** [comment]
Thank you for your quick reply. I assigned the parameter "img-size" as [1280, 2048].  I exported the ONNX, the following are the output : 

`args Namespace(backbone='vgg16_bn', row=2, line=2, img_size=[1280, 2048], batch_size=1, weight_path='weights/SHTechA.pth', device='cpu', simplify=True)
/home/user/Documents/crowd/CrowdCounting-P2PNet/models/p2pnet.py:138: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  image_shape = np.array(image_shape)
/home/user/Documents/crowd/CrowdCounting-P2PNet/models/p2pnet.py:153: TracerWarning: torch.from_numpy results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  return torch.from_numpy(all_anchor_points.astype(np.float32))
============= Diagnostic Run torch.onnx.export version 2.0.1+cu117 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================
Starting to simplify ONNX...
Simplifier failure: /project/third_party/onnx-optimizer/onnxoptimizer/passes/eliminate_shape_gather.h:48: runTransform: Assertion `indices_val < dims.size()` failed.
ONNX export success, saved as weights/SHTechA.onnx`

I then run the _inference_onnx.py_  with the ShanghaiTech Part A Test images (ShanghaiTech/part_A/test_data/images/). Here is the output error : 

`img_name =  IMG_99.jpg, width =  640  height =  480
2023-08-31 09:30:49.226018202 [E:onnxruntime:, sequential_executor.cc:514 ExecuteKernel] Non-zero status code returned while running Add node. Name:'/Add' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/math/element_wise_ops.h:560 void onnxruntime::BroadcastIterator::Append(ptrdiff_t, ptrdiff_t) axis == 1 || axis == largest was false. Attempting to broadcast an axis by a dimension other than 1. 15360 by 163840
Traceback (most recent call last):
  File "/home/user/Documents/crowd/CrowdCounting-P2PNet/inference_onnx.py", line 90, in <module>
    main(args)
  File "/home/user/Documents/crowd/CrowdCounting-P2PNet/inference_onnx.py", line 69, in main
    process_one_image(dir_path, img_name, transform, session)
  File "/home/user/Documents/crowd/CrowdCounting-P2PNet/inference_onnx.py", line 30, in process_one_image
    pred_logits, pred_points = session.run(['pred_logits', 'pred_points'], ort_inputs)
  File "/home/user/.local/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 217, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Add node. Name:'/Add' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/math/element_wise_ops.h:560 void onnxruntime::BroadcastIterator::Append(ptrdiff_t, ptrdiff_t) axis == 1 || axis == largest was false. Attempting to broadcast an axis by a dimension other than 1. 15360 by 163840`

I would be very happy, if you help.

**Comment by y-1111-y** [comment]
Thanks for your reply, and I think I know the reason that causes the error. The reason is that, when you generate the onnx file from your pth file, some calculations results are simplified to the constants. And the simplified results are related to the image size. And you can use this [website](https://netron.app/) to see your model ship by uploading the onnx file, and you may find that some layers in the end of your model use the constants(163840).

You can try to use the same image size(640*480) when you run both the [export.py](https://github.com/y-1111-y/P2Pnet_onnx/blob/main/export.py) and [inference_onnx](https://github.com/y-1111-y/P2Pnet_onnx/blob/main/inference_onnx). It may work.

I hope this can help you.

**Comment by ycbilge** [comment]
Thank you very much for your response. I think we need to change the model constants and make them dynamics. 
All the best.

**Comment by jdmking2019** [comment]
> Thank you very much for your response. I think we need to change the model constants and make them dynamics. All the best.

 I have also encountered the same problem. Have you resolved it？

**Comment by ycbilge** [comment]
No. I hope somebody will resolve it and share here.

**Comment by Moji0110** [comment]
hi. i have a problem with onnx model. i use your code to convert pth model to onnx. i set the input size to 1280x720 and convert the model. and there is no problem in converting but the problem is output of the model. in pth model i also use the input size 1280x720 and feed it to pth model. the output of pth model is a dictionary that contains two part: pred_logits and pred_points. the size of these tensors are [1,21504,2] but the output of the onnx model is a list that consist of two [1,57500,2] that are different from pth output. i dont know what is the problem. would you please help me?

**Comment by y-1111-y** [comment]
> hi. i have a problem with onnx model. i use your code to convert pth model to onnx. i set the input size to 1280x720 and convert the model. and there is no problem in converting but the problem is output of the model. in pth model i also use the input size 1280x720 and feed it to pth model. the output of pth model is a dictionary that contains two part: pred_logits and pred_points. the size of these tensors are [1,21504,2] but the output of the onnx model is a list that consist of two [1,57500,2] that are different from pth output. i dont know what is the problem. would you please help me?

Thanks for your comment. And I try to run the code with the 1280x720 image size. But I get 2 tensors with the shape of **_[1,57600,2]_** form pth model  which are different from yours. I think the 57600 is correct because **_57600=(1280/8)*(720/8)*4_**. 
I guess your difference happens when you resized your images before your model read the them.

**Comment by Moji0110** [comment]
> > hi. i have a problem with onnx model. i use your code to convert pth model to onnx. i set the input size to 1280x720 and convert the model. and there is no problem in converting but the problem is output of the model. in pth model i also use the input size 1280x720 and feed it to pth model. the output of pth model is a dictionary that contains two part: pred_logits and pred_points. the size of these tensors are [1,21504,2] but the output of the onnx model is a list that consist of two [1,57500,2] that are different from pth output. i dont know what is the problem. would you please help me?
> 
> Thanks for your comment. And I try to run the code with the 1280x720 image size. But I get 2 tensors with the shape of **_[1,57600,2]_** form pth model which are different from yours. I think the 57600 is correct because **_57600=(1280/8)*(720/8)*4_**. I guess your difference happens when you resized your images before your model read the them.

you were right, that was my mistake i change the input size and it works properly but there is another problem. the output coordinates of onnx model are correct but the i think the confidences for coordinates are incorrect and this is my code:

onnx_session= onnxrt.InferenceSession("/home/mojtaba/crowd_estimation_tahernia/CrowdCounting-P2PNet-main/CrowdCounting-P2PNet-main/weights/SHTechA.onnx",providers=['CUDAExecutionProvider'])
frame=cv2.imread('/home/mojtaba/crowd_estimation_tahernia/CrowdCounting-P2PNet-main/CrowdCounting-P2PNet-main/inference/test2.jpg')
frame=cv2.cvtColor(frame,cv2.COLOR_BGR2RGB)
img2=cv2.resize(frame,(1280,720))
img1=img2.astype(np.float32)
img=img1/255.
img=img.transpose((2,0,1))
img=np.expand_dims(img,0)
onnx_inputs= {onnx_session.get_inputs()[0].name:img}

outputs_logits_points = onnx_session.run(None, onnx_inputs)
outputs_scores = torch.nn.functional.softmax(torch.tensor(outputs_logits_points[0]), -1)[:, :, 1][0]
outputs_points = outputs_logits_points[1]
outputs_points=outputs_points.squeeze()
outputs_points[:,[0,1]]=outputs_points[:,[1,0]]

######################################################################
this is the output confidence for onnx model:
[[[ 3.8512692, -5.534392 ],
        [ 4.803897 , -4.8207283],
        [ 4.29532  , -4.724397 ],
        ...,
        [ 2.0202012, -1.8127632],
        [ 1.9735465, -1.9210513],
        [ 2.4479744, -2.3777225]]]
######################################################################
and this is the output for pth model:
[[[ 4.0802, -6.1222],
         [ 5.1626, -5.0993],
         [ 4.6970, -5.1152],
         ...,
         [ 1.9716, -1.8766],
         [ 2.2144, -2.1158],
         [ 2.8148, -2.5304]]]

**Comment by Moji0110** [comment]
i know these outputs shouldn't be exactly same but the results on same image and same threshold are quite different and i think this is because of pred_logits

**Comment by y-1111-y** [comment]
> i know these outputs shouldn't be exactly same but the results on same image and same threshold are quite different and i think this is because of pred_logits

I tried to use the tensors whose values are all zeros or all ones to test. And I find the results are the same from onnx and pth models. So I think the reason is that you used different image preprocessing methods.
You can see your model's input value, and see if the inputs for the onnx model and the pth model are the same.

**Comment by Moji0110** [comment]
> > i know these outputs shouldn't be exactly same but the results on same image and same threshold are quite different and i think this is because of pred_logits
> 
> I tried to use the tensors whose values are all zeros or all ones to test. And I find the results are the same from onnx and pth models. So I think the reason is that you used different image preprocessing methods. You can see your model's input value, and see if the inputs for the onnx model and the pth model are the same.

i use inference_onnx.py for inference the onnx model and use your preprocessing and also this preprocessing in pth inference but still same conclusion. i found the problem but i cant solve it. the problem is output_points from onnx model. the confidences were same in both models i mean exactly the same but the output_points were different. i saved both confidence and output_points of both model in a .csv file and check both values in confidence and output_points. confidences were equal and output_points were different. i also have csv files if you want i will send them to your email and please test both onnx and pth model on an image because you said you tested two models on a all one tensor and all zero tensor and for being sure please check it on a crowd image and let me know the results and i would be so thankful here is my code:

################# ONNX INFERENCE CODE ##############################

img_path = os.path.join(dir_path, img_name) 

img_raw = Image.open(img_path).convert('RGB')
width, height = img_raw.size 
if width < height:
    img_raw = img_raw.transpose(Image.ROTATE_90)
width, height = img_raw.size
new_width = width // 128 * 128
new_height = height // 128 * 128
#print(new_height,new_width)
img_raw = img_raw.resize((1280, 720), Image.ANTIALIAS)

img = transform(img_raw)
samples = torch.Tensor(img).unsqueeze(0)


ort_inputs = {'input': samples.numpy()}
print(ort_inputs['input'].shape)
pred_logits, pred_points = session.run(['pred_logits', 'pred_points'], ort_inputs)

########################## PTH INFERENCE ###########################

img_path = "/home/mojtaba/crowd_estimation_tahernia/CrowdCounting-P2PNet-main/CrowdCounting-P2PNet-main/inference/test2.jpg"

img_raw = Image.open(img_path).convert('RGB')
#img_raw = Image.open(img_path).convert('RGB')
width, height = img_raw.size #PIL image 
if width < height:
    img_raw = img_raw.transpose(Image.ROTATE_90)
width, height = img_raw.size
new_width = width // 128 * 128
new_height = height // 128 * 128
#print(new_height,new_width)
img_raw = img_raw.resize((1280, 720), Image.ANTIALIAS)

img = transform(img_raw)
samples = torch.Tensor(img).unsqueeze(0)
samples = samples.to(device)
outputs = model(samples)

**Comment by Moji0110** [comment]
i also use a tensor whose values are all one and and i get same results that pred_points are quite different in onnx and pth model.

**Comment by y-1111-y** [comment]
> i also use a tensor whose values are all one and and i get same results that pred_points are quite different in onnx and pth model.

I see your problem, but I am very sure that I can get the same pred_logits and pred_points results of the same real image from onnx and pth model.
I think the reason may be that you don't use the newest onnx model you generated. You'd better find the reason by yourself.
And I will modify my code to help you avoid your problem. Please use my the newest code and try again.

**Comment by Moji0110** [comment]
Thank you very much. I use your new code and it works and the outputs are the same. There is one other question. Why the inference time not much different? I test both models on a video and the difference is 10 to 20 Ms between them. I expect that the inference time from onnx will be much lower.

**Comment by y-1111-y** [comment]
> Thank you very much. I use your new code and it works and the outputs are the same. There is one other question. Why the inference time not much different? I test both models on a video and the difference is 10 to 20 Ms between them. I expect that the inference time from onnx will be much lower.

The onnx model just not reduces the inference time but also reduce the memory used. So you can use a lager batch_size to get a considerable promotion.

**Comment by Zalways** [comment]
> 1280x720 a

have you solved this problem? i met the same problem!  hope someone can help!

**Comment by yuxiaoz** [comment]
So, why set dynamic axes for input width and height, "add" error occurs?
